//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LabelInfoServiceBinding", Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicHeadEntity))]
public partial class LabelInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getPurchaseOrdersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUnconfirmedPrintOrdersOperationCompleted;
    
    private System.Threading.SendOrPostCallback confirmPrintOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback requestPrintOrderOperationCompleted;
    
    private System.Threading.SendOrPostCallback getActiveSuppliersOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkSystemOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUnconfirmedPurchaseOrdersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getStornoPurchaseOrdersOperationCompleted;
    
    /// <remarks/>
    public LabelInfoService() {
        this.Url = "https://webservices.gerryweber-ag.de:8443/LabelInfoWebService/services/LabelInfoS" +
            "ervice";
    }
    
    /// <remarks/>
    public event getPurchaseOrdersCompletedEventHandler getPurchaseOrdersCompleted;
    
    /// <remarks/>
    public event getUnconfirmedPrintOrdersCompletedEventHandler getUnconfirmedPrintOrdersCompleted;
    
    /// <remarks/>
    public event confirmPrintOrderCompletedEventHandler confirmPrintOrderCompleted;
    
    /// <remarks/>
    public event requestPrintOrderCompletedEventHandler requestPrintOrderCompleted;
    
    /// <remarks/>
    public event getActiveSuppliersCompletedEventHandler getActiveSuppliersCompleted;
    
    /// <remarks/>
    public event checkSystemCompletedEventHandler checkSystemCompleted;
    
    /// <remarks/>
    public event getUnconfirmedPurchaseOrdersCompletedEventHandler getUnconfirmedPurchaseOrdersCompleted;
    
    /// <remarks/>
    public event getStornoPurchaseOrdersCompletedEventHandler getStornoPurchaseOrdersCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/getPurchaseOrders", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PurchaseOrderHead[] getPurchaseOrders([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime pDifferenceStart, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime pDifferenceEnd) {
        object[] results = this.Invoke("getPurchaseOrders", new object[] {
                    pDifferenceStart,
                    pDifferenceEnd});
        return ((PurchaseOrderHead[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPurchaseOrders(System.DateTime pDifferenceStart, System.DateTime pDifferenceEnd, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPurchaseOrders", new object[] {
                    pDifferenceStart,
                    pDifferenceEnd}, callback, asyncState);
    }
    
    /// <remarks/>
    public PurchaseOrderHead[] EndgetPurchaseOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PurchaseOrderHead[])(results[0]));
    }
    
    /// <remarks/>
    public void getPurchaseOrdersAsync(System.DateTime pDifferenceStart, System.DateTime pDifferenceEnd) {
        this.getPurchaseOrdersAsync(pDifferenceStart, pDifferenceEnd, null);
    }
    
    /// <remarks/>
    public void getPurchaseOrdersAsync(System.DateTime pDifferenceStart, System.DateTime pDifferenceEnd, object userState) {
        if ((this.getPurchaseOrdersOperationCompleted == null)) {
            this.getPurchaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPurchaseOrdersOperationCompleted);
        }
        this.InvokeAsync("getPurchaseOrders", new object[] {
                    pDifferenceStart,
                    pDifferenceEnd}, this.getPurchaseOrdersOperationCompleted, userState);
    }
    
    private void OngetPurchaseOrdersOperationCompleted(object arg) {
        if ((this.getPurchaseOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPurchaseOrdersCompleted(this, new getPurchaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/getUnconfirmedPrintOrd" +
        "ers", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintOrderHead[] getUnconfirmedPrintOrders([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pCompany) {
        object[] results = this.Invoke("getUnconfirmedPrintOrders", new object[] {
                    pCompany});
        return ((PrintOrderHead[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUnconfirmedPrintOrders(int pCompany, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUnconfirmedPrintOrders", new object[] {
                    pCompany}, callback, asyncState);
    }
    
    /// <remarks/>
    public PrintOrderHead[] EndgetUnconfirmedPrintOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PrintOrderHead[])(results[0]));
    }
    
    /// <remarks/>
    public void getUnconfirmedPrintOrdersAsync(int pCompany) {
        this.getUnconfirmedPrintOrdersAsync(pCompany, null);
    }
    
    /// <remarks/>
    public void getUnconfirmedPrintOrdersAsync(int pCompany, object userState) {
        if ((this.getUnconfirmedPrintOrdersOperationCompleted == null)) {
            this.getUnconfirmedPrintOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnconfirmedPrintOrdersOperationCompleted);
        }
        this.InvokeAsync("getUnconfirmedPrintOrders", new object[] {
                    pCompany}, this.getUnconfirmedPrintOrdersOperationCompleted, userState);
    }
    
    private void OngetUnconfirmedPrintOrdersOperationCompleted(object arg) {
        if ((this.getUnconfirmedPrintOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUnconfirmedPrintOrdersCompleted(this, new getUnconfirmedPrintOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/confirmPrintOrder", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool confirmPrintOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pPrintOrderId) {
        object[] results = this.Invoke("confirmPrintOrder", new object[] {
                    pPrintOrderId});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconfirmPrintOrder(int pPrintOrderId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("confirmPrintOrder", new object[] {
                    pPrintOrderId}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndconfirmPrintOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void confirmPrintOrderAsync(int pPrintOrderId) {
        this.confirmPrintOrderAsync(pPrintOrderId, null);
    }
    
    /// <remarks/>
    public void confirmPrintOrderAsync(int pPrintOrderId, object userState) {
        if ((this.confirmPrintOrderOperationCompleted == null)) {
            this.confirmPrintOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmPrintOrderOperationCompleted);
        }
        this.InvokeAsync("confirmPrintOrder", new object[] {
                    pPrintOrderId}, this.confirmPrintOrderOperationCompleted, userState);
    }
    
    private void OnconfirmPrintOrderOperationCompleted(object arg) {
        if ((this.confirmPrintOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.confirmPrintOrderCompleted(this, new confirmPrintOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/requestPrintOrder", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintOrderHead requestPrintOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] PrintRequestHead pPrintRequest) {
        object[] results = this.Invoke("requestPrintOrder", new object[] {
                    pPrintRequest});
        return ((PrintOrderHead)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginrequestPrintOrder(PrintRequestHead pPrintRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("requestPrintOrder", new object[] {
                    pPrintRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public PrintOrderHead EndrequestPrintOrder(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PrintOrderHead)(results[0]));
    }
    
    /// <remarks/>
    public void requestPrintOrderAsync(PrintRequestHead pPrintRequest) {
        this.requestPrintOrderAsync(pPrintRequest, null);
    }
    
    /// <remarks/>
    public void requestPrintOrderAsync(PrintRequestHead pPrintRequest, object userState) {
        if ((this.requestPrintOrderOperationCompleted == null)) {
            this.requestPrintOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestPrintOrderOperationCompleted);
        }
        this.InvokeAsync("requestPrintOrder", new object[] {
                    pPrintRequest}, this.requestPrintOrderOperationCompleted, userState);
    }
    
    private void OnrequestPrintOrderOperationCompleted(object arg) {
        if ((this.requestPrintOrderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.requestPrintOrderCompleted(this, new requestPrintOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/getActiveSuppliers", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Supplier[] getActiveSuppliers([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pCompany) {
        object[] results = this.Invoke("getActiveSuppliers", new object[] {
                    pCompany});
        return ((Supplier[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetActiveSuppliers(int pCompany, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getActiveSuppliers", new object[] {
                    pCompany}, callback, asyncState);
    }
    
    /// <remarks/>
    public Supplier[] EndgetActiveSuppliers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Supplier[])(results[0]));
    }
    
    /// <remarks/>
    public void getActiveSuppliersAsync(int pCompany) {
        this.getActiveSuppliersAsync(pCompany, null);
    }
    
    /// <remarks/>
    public void getActiveSuppliersAsync(int pCompany, object userState) {
        if ((this.getActiveSuppliersOperationCompleted == null)) {
            this.getActiveSuppliersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetActiveSuppliersOperationCompleted);
        }
        this.InvokeAsync("getActiveSuppliers", new object[] {
                    pCompany}, this.getActiveSuppliersOperationCompleted, userState);
    }
    
    private void OngetActiveSuppliersOperationCompleted(object arg) {
        if ((this.getActiveSuppliersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getActiveSuppliersCompleted(this, new getActiveSuppliersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/checkSystem", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string checkSystem([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pValue) {
        object[] results = this.Invoke("checkSystem", new object[] {
                    pValue});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckSystem(string pValue, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkSystem", new object[] {
                    pValue}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcheckSystem(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void checkSystemAsync(string pValue) {
        this.checkSystemAsync(pValue, null);
    }
    
    /// <remarks/>
    public void checkSystemAsync(string pValue, object userState) {
        if ((this.checkSystemOperationCompleted == null)) {
            this.checkSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckSystemOperationCompleted);
        }
        this.InvokeAsync("checkSystem", new object[] {
                    pValue}, this.checkSystemOperationCompleted, userState);
    }
    
    private void OncheckSystemOperationCompleted(object arg) {
        if ((this.checkSystemCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkSystemCompleted(this, new checkSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/getUnconfirmedPurchase" +
        "Orders", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public POHead[] getUnconfirmedPurchaseOrders([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pCompany) {
        object[] results = this.Invoke("getUnconfirmedPurchaseOrders", new object[] {
                    pCompany});
        return ((POHead[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUnconfirmedPurchaseOrders(int pCompany, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUnconfirmedPurchaseOrders", new object[] {
                    pCompany}, callback, asyncState);
    }
    
    /// <remarks/>
    public POHead[] EndgetUnconfirmedPurchaseOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POHead[])(results[0]));
    }
    
    /// <remarks/>
    public void getUnconfirmedPurchaseOrdersAsync(int pCompany) {
        this.getUnconfirmedPurchaseOrdersAsync(pCompany, null);
    }
    
    /// <remarks/>
    public void getUnconfirmedPurchaseOrdersAsync(int pCompany, object userState) {
        if ((this.getUnconfirmedPurchaseOrdersOperationCompleted == null)) {
            this.getUnconfirmedPurchaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnconfirmedPurchaseOrdersOperationCompleted);
        }
        this.InvokeAsync("getUnconfirmedPurchaseOrders", new object[] {
                    pCompany}, this.getUnconfirmedPurchaseOrdersOperationCompleted, userState);
    }
    
    private void OngetUnconfirmedPurchaseOrdersOperationCompleted(object arg) {
        if ((this.getUnconfirmedPurchaseOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUnconfirmedPurchaseOrdersCompleted(this, new getUnconfirmedPurchaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.gerryweber-ag.de:8443/LabelInfoService/getStornoPurchaseOrder" +
        "s", RequestNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", ResponseNamespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public POStornoHead[] getStornoPurchaseOrders([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int pCompany) {
        object[] results = this.Invoke("getStornoPurchaseOrders", new object[] {
                    pCompany});
        return ((POStornoHead[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetStornoPurchaseOrders(int pCompany, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getStornoPurchaseOrders", new object[] {
                    pCompany}, callback, asyncState);
    }
    
    /// <remarks/>
    public POStornoHead[] EndgetStornoPurchaseOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POStornoHead[])(results[0]));
    }
    
    /// <remarks/>
    public void getStornoPurchaseOrdersAsync(int pCompany) {
        this.getStornoPurchaseOrdersAsync(pCompany, null);
    }
    
    /// <remarks/>
    public void getStornoPurchaseOrdersAsync(int pCompany, object userState) {
        if ((this.getStornoPurchaseOrdersOperationCompleted == null)) {
            this.getStornoPurchaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStornoPurchaseOrdersOperationCompleted);
        }
        this.InvokeAsync("getStornoPurchaseOrders", new object[] {
                    pCompany}, this.getStornoPurchaseOrdersOperationCompleted, userState);
    }
    
    private void OngetStornoPurchaseOrdersOperationCompleted(object arg) {
        if ((this.getStornoPurchaseOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getStornoPurchaseOrdersCompleted(this, new getStornoPurchaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PurchaseOrderHead : BasicHeadEntity {
    
    private int companyField;
    
    private int seasonField;
    
    private int po_numberField;
    
    private int po_idField;
    
    private int po_styleField;
    
    private int po_articleField;
    
    private int po_supplierField;
    
    private string po_locationField;
    
    private System.Nullable<int> po_prioField;
    
    private string style_nameField;
    
    private string style_lengthField;
    
    private int production_typeField;
    
    private int collectionprogField;
    
    private string po_productgrouptextField;
    
    private string po_productinfoField;
    
    private string po_nosField;
    
    private string po_outerfabricField;
    
    private string care_labelpage2_text1Field;
    
    private string care_labelpage2_text2Field;
    
    private string care_labelpage2_text3Field;
    
    private string care_labelpage2_text4Field;
    
    private string care_labelpage2_text5Field;
    
    private string care_labelpage2_text6Field;
    
    private string care_labelpage2_text7Field;
    
    private Price[] priceField;
    
    private PurchaseOrderStyleData[] stylesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_number {
        get {
            return this.po_numberField;
        }
        set {
            this.po_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_id {
        get {
            return this.po_idField;
        }
        set {
            this.po_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_style {
        get {
            return this.po_styleField;
        }
        set {
            this.po_styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_article {
        get {
            return this.po_articleField;
        }
        set {
            this.po_articleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_supplier {
        get {
            return this.po_supplierField;
        }
        set {
            this.po_supplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string po_location {
        get {
            return this.po_locationField;
        }
        set {
            this.po_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> po_prio {
        get {
            return this.po_prioField;
        }
        set {
            this.po_prioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string style_name {
        get {
            return this.style_nameField;
        }
        set {
            this.style_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string style_length {
        get {
            return this.style_lengthField;
        }
        set {
            this.style_lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int production_type {
        get {
            return this.production_typeField;
        }
        set {
            this.production_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int collectionprog {
        get {
            return this.collectionprogField;
        }
        set {
            this.collectionprogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_productgrouptext {
        get {
            return this.po_productgrouptextField;
        }
        set {
            this.po_productgrouptextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_productinfo {
        get {
            return this.po_productinfoField;
        }
        set {
            this.po_productinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_nos {
        get {
            return this.po_nosField;
        }
        set {
            this.po_nosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_outerfabric {
        get {
            return this.po_outerfabricField;
        }
        set {
            this.po_outerfabricField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text1 {
        get {
            return this.care_labelpage2_text1Field;
        }
        set {
            this.care_labelpage2_text1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text2 {
        get {
            return this.care_labelpage2_text2Field;
        }
        set {
            this.care_labelpage2_text2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text3 {
        get {
            return this.care_labelpage2_text3Field;
        }
        set {
            this.care_labelpage2_text3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text4 {
        get {
            return this.care_labelpage2_text4Field;
        }
        set {
            this.care_labelpage2_text4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text5 {
        get {
            return this.care_labelpage2_text5Field;
        }
        set {
            this.care_labelpage2_text5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text6 {
        get {
            return this.care_labelpage2_text6Field;
        }
        set {
            this.care_labelpage2_text6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_labelpage2_text7 {
        get {
            return this.care_labelpage2_text7Field;
        }
        set {
            this.care_labelpage2_text7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Price[] price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("styles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PurchaseOrderStyleData[] styles {
        get {
            return this.stylesField;
        }
        set {
            this.stylesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class Price {
    
    private string countryField;
    
    private double priceField;
    
    private string currencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class POStornoHead {
    
    private int companyField;
    
    private int seasonField;
    
    private int po_numberField;
    
    private int po_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_number {
        get {
            return this.po_numberField;
        }
        set {
            this.po_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_id {
        get {
            return this.po_idField;
        }
        set {
            this.po_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintRequestQuantitys {
    
    private int po_posField;
    
    private string po_sizeField;
    
    private int quantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_pos {
        get {
            return this.po_posField;
        }
        set {
            this.po_posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_size {
        get {
            return this.po_sizeField;
        }
        set {
            this.po_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintRequestPosition {
    
    private int posField;
    
    private string label_typeField;
    
    private PrintRequestQuantitys[] quantitysField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label_type {
        get {
            return this.label_typeField;
        }
        set {
            this.label_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quantitys", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintRequestQuantitys[] quantitys {
        get {
            return this.quantitysField;
        }
        set {
            this.quantitysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintOrderLot {
    
    private string sizeField;
    
    private int size_amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int size_amount {
        get {
            return this.size_amountField;
        }
        set {
            this.size_amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintOrderIdents {
    
    private int po_posField;
    
    private string po_sizeField;
    
    private string epc_startField;
    
    private string epc_endField;
    
    private System.Nullable<int> ident_startField;
    
    private System.Nullable<int> ident_endField;
    
    private int quantityField;
    
    private PrintOrderLot[] lot_positionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_pos {
        get {
            return this.po_posField;
        }
        set {
            this.po_posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_size {
        get {
            return this.po_sizeField;
        }
        set {
            this.po_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string epc_start {
        get {
            return this.epc_startField;
        }
        set {
            this.epc_startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string epc_end {
        get {
            return this.epc_endField;
        }
        set {
            this.epc_endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> ident_start {
        get {
            return this.ident_startField;
        }
        set {
            this.ident_startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> ident_end {
        get {
            return this.ident_endField;
        }
        set {
            this.ident_endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lot_positions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintOrderLot[] lot_positions {
        get {
            return this.lot_positionsField;
        }
        set {
            this.lot_positionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintOrderPosition {
    
    private int posField;
    
    private string label_typeField;
    
    private PrintOrderIdents[] identsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label_type {
        get {
            return this.label_typeField;
        }
        set {
            this.label_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idents", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintOrderIdents[] idents {
        get {
            return this.identsField;
        }
        set {
            this.identsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class Size {
    
    private string countrysizeField;
    
    private string countrysizetextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string countrysize {
        get {
            return this.countrysizeField;
        }
        set {
            this.countrysizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countrysizetext {
        get {
            return this.countrysizetextField;
        }
        set {
            this.countrysizetextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PurchaseOrderDetail {
    
    private string po_sizeField;
    
    private string po_eanField;
    
    private int po_quantityField;
    
    private Size[] countrysize_arrayField;
    
    private Size[] countrysize_array2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_size {
        get {
            return this.po_sizeField;
        }
        set {
            this.po_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_ean {
        get {
            return this.po_eanField;
        }
        set {
            this.po_eanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_quantity {
        get {
            return this.po_quantityField;
        }
        set {
            this.po_quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("countrysize_array", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Size[] countrysize_array {
        get {
            return this.countrysize_arrayField;
        }
        set {
            this.countrysize_arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("countrysize_array2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Size[] countrysize_array2 {
        get {
            return this.countrysize_array2Field;
        }
        set {
            this.countrysize_array2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PurchaseOrderStyleData {
    
    private int po_posField;
    
    private int po_colourField;
    
    private int po_styleField;
    
    private int po_articleField;
    
    private int po_duedateField;
    
    private string po_customer_dateField;
    
    private string po_groupField;
    
    private int po_themeField;
    
    private string po_theme_descField;
    
    private string po_replenishmentField;
    
    private string po_printmodeField;
    
    private string caresymbolsField;
    
    private string print_seasonField;
    
    private string[] label_typeField;
    
    private PurchaseOrderDetail[] size_positionsField;
    
    private string care_label_page_de_contField;
    
    private string care_label_page_de_careField;
    
    private string care_label_page_de_addonField;
    
    private string[] care_label_page_isoField;
    
    private string care_label_made_inField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_pos {
        get {
            return this.po_posField;
        }
        set {
            this.po_posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_colour {
        get {
            return this.po_colourField;
        }
        set {
            this.po_colourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_style {
        get {
            return this.po_styleField;
        }
        set {
            this.po_styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_article {
        get {
            return this.po_articleField;
        }
        set {
            this.po_articleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_duedate {
        get {
            return this.po_duedateField;
        }
        set {
            this.po_duedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_customer_date {
        get {
            return this.po_customer_dateField;
        }
        set {
            this.po_customer_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_group {
        get {
            return this.po_groupField;
        }
        set {
            this.po_groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_theme {
        get {
            return this.po_themeField;
        }
        set {
            this.po_themeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string po_theme_desc {
        get {
            return this.po_theme_descField;
        }
        set {
            this.po_theme_descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_replenishment {
        get {
            return this.po_replenishmentField;
        }
        set {
            this.po_replenishmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string po_printmode {
        get {
            return this.po_printmodeField;
        }
        set {
            this.po_printmodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string caresymbols {
        get {
            return this.caresymbolsField;
        }
        set {
            this.caresymbolsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string print_season {
        get {
            return this.print_seasonField;
        }
        set {
            this.print_seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("label_type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string[] label_type {
        get {
            return this.label_typeField;
        }
        set {
            this.label_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("size_positions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PurchaseOrderDetail[] size_positions {
        get {
            return this.size_positionsField;
        }
        set {
            this.size_positionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_label_page_de_cont {
        get {
            return this.care_label_page_de_contField;
        }
        set {
            this.care_label_page_de_contField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_label_page_de_care {
        get {
            return this.care_label_page_de_careField;
        }
        set {
            this.care_label_page_de_careField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_label_page_de_addon {
        get {
            return this.care_label_page_de_addonField;
        }
        set {
            this.care_label_page_de_addonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("care_label_page_iso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] care_label_page_iso {
        get {
            return this.care_label_page_isoField;
        }
        set {
            this.care_label_page_isoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string care_label_made_in {
        get {
            return this.care_label_made_inField;
        }
        set {
            this.care_label_made_inField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(POHead))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Supplier))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintRequestHead))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintOrderHead))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PurchaseOrderHead))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class BasicHeadEntity {
    
    private int datrefField;
    
    private System.DateTime transmission_timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int datref {
        get {
            return this.datrefField;
        }
        set {
            this.datrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime transmission_time {
        get {
            return this.transmission_timeField;
        }
        set {
            this.transmission_timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class POHead : BasicHeadEntity {
    
    private int po_id_serField;
    
    private PurchaseOrderHead poField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_id_ser {
        get {
            return this.po_id_serField;
        }
        set {
            this.po_id_serField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PurchaseOrderHead po {
        get {
            return this.poField;
        }
        set {
            this.poField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class Supplier : BasicHeadEntity {
    
    private int companyField;
    
    private int supplier_idField;
    
    private string supplier_name1Field;
    
    private string supplier_name2Field;
    
    private string streetField;
    
    private string zipcodeField;
    
    private string cityField;
    
    private string countryField;
    
    private string phoneField;
    
    private string emailField;
    
    private string print_locationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int supplier_id {
        get {
            return this.supplier_idField;
        }
        set {
            this.supplier_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string supplier_name1 {
        get {
            return this.supplier_name1Field;
        }
        set {
            this.supplier_name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string supplier_name2 {
        get {
            return this.supplier_name2Field;
        }
        set {
            this.supplier_name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string print_location {
        get {
            return this.print_locationField;
        }
        set {
            this.print_locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintRequestHead : BasicHeadEntity {
    
    private string prr_idField;
    
    private int companyField;
    
    private int seasonField;
    
    private int po_numberField;
    
    private string pro_locationField;
    
    private int prr_typeField;
    
    private int prr_prioField;
    
    private PrintRequestPosition[] positionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string prr_id {
        get {
            return this.prr_idField;
        }
        set {
            this.prr_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_number {
        get {
            return this.po_numberField;
        }
        set {
            this.po_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pro_location {
        get {
            return this.pro_locationField;
        }
        set {
            this.pro_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int prr_type {
        get {
            return this.prr_typeField;
        }
        set {
            this.prr_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int prr_prio {
        get {
            return this.prr_prioField;
        }
        set {
            this.prr_prioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("positions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintRequestPosition[] positions {
        get {
            return this.positionsField;
        }
        set {
            this.positionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.gerryweber-ag.de:8443/LabelInfoService/")]
public partial class PrintOrderHead : BasicHeadEntity {
    
    private int pro_idField;
    
    private int po_idField;
    
    private int pro_typeField;
    
    private string pro_locationField;
    
    private int pro_prioField;
    
    private PrintOrderPosition[] positionsField;
    
    private PurchaseOrderHead purchaseorderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int pro_id {
        get {
            return this.pro_idField;
        }
        set {
            this.pro_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int po_id {
        get {
            return this.po_idField;
        }
        set {
            this.po_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int pro_type {
        get {
            return this.pro_typeField;
        }
        set {
            this.pro_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pro_location {
        get {
            return this.pro_locationField;
        }
        set {
            this.pro_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int pro_prio {
        get {
            return this.pro_prioField;
        }
        set {
            this.pro_prioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("positions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PrintOrderPosition[] positions {
        get {
            return this.positionsField;
        }
        set {
            this.positionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PurchaseOrderHead purchaseorder {
        get {
            return this.purchaseorderField;
        }
        set {
            this.purchaseorderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getPurchaseOrdersCompletedEventHandler(object sender, getPurchaseOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPurchaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPurchaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PurchaseOrderHead[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PurchaseOrderHead[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getUnconfirmedPrintOrdersCompletedEventHandler(object sender, getUnconfirmedPrintOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUnconfirmedPrintOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUnconfirmedPrintOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PrintOrderHead[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PrintOrderHead[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void confirmPrintOrderCompletedEventHandler(object sender, confirmPrintOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class confirmPrintOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal confirmPrintOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void requestPrintOrderCompletedEventHandler(object sender, requestPrintOrderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class requestPrintOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal requestPrintOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PrintOrderHead Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PrintOrderHead)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getActiveSuppliersCompletedEventHandler(object sender, getActiveSuppliersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getActiveSuppliersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getActiveSuppliersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Supplier[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Supplier[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void checkSystemCompletedEventHandler(object sender, checkSystemCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getUnconfirmedPurchaseOrdersCompletedEventHandler(object sender, getUnconfirmedPurchaseOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUnconfirmedPurchaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUnconfirmedPurchaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public POHead[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((POHead[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getStornoPurchaseOrdersCompletedEventHandler(object sender, getStornoPurchaseOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getStornoPurchaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getStornoPurchaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public POStornoHead[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((POStornoHead[])(this.results[0]));
        }
    }
}
